### PR TITLE
fix(layout): update page template for eXist-design and plain

### PR DESCRIPTION
**Pull request by flamminger**
Updated the templates for the eXist-Design and plain (option).

### CODE REVIEW

**Comment by duncdrum** [comment]
Thank you for the PR. This is great and I had been meaning to do this a while back. We would need to port the navbar changes to a few more html template files from the looks of it. To see if they can be included in other designs. 

I ll do some testing on the weekend to make sure things are working as intended. Could you maybe add a screenshot of a generated plain app with you changes applied.

**Review by duncdrum — COMMENTED** [review]
This looks good in principle. Could you please adjust the commit message according to the template mentioned in the readme. Otherwise the release bot won't know what to do with this.

**Comment by flamminger** [comment]
I have updated the commit message and also updated the eXist-Design Template.

exist-design-small
exist-design
plain-design-small
plain-design
.

**Review by duncdrum — APPROVED** [review]
Thank you very much for your contribution. There are some further BS `5` tweaks that I have lying around, but those aren't finished yet. Happy to merge this.

**Pull request merged**
